heat_template_version: 2018-08-31

description: >
  Template básico para crear una instancia, asignarle un puerto Neutron
  y una IP flotante desde la red pública.

parameters:
  image:
    type: string
    description: "Imagen a utilizar para la instancia"
  flavor:
    type: string
    description: "Flavor utilizado para la máquina"
  network:
    type: string
    description: "UUID o nombre de la red interna"
  key_name:
    type: string
    description: "Par de claves SSH a inyectar en la instancia"
  public_network:
    type: string
    description: "Red pública desde la que asignar la IP flotante"

resources:
  server_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }

  my_server:
    type: OS::Nova::Server
    properties:
      name: demo-server
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: server_port }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }

  floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: server_port }

outputs:
  instance_name:
    description: "Nombre de la instancia creada"
    value: { get_attr: [my_server, name] }

  fixed_ip_address:
    description: "Dirección IP fija interna asignada al puerto"
    value: { get_attr: [server_port, fixed_ips, 0, ip_address] }

  floating_ip_address:
    description: "IP flotante asignada a la instancia"
    value: { get_attr: [floating_ip, floating_ip_address] }
